# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-21 22:09
from __future__ import unicode_literals

import Apps.WorkOrdersApp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WorkOrdersApp', '0002_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to=Apps.WorkOrdersApp.models.get_upload_path)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkOrdersApp.Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Documents',
                'verbose_name': 'Document',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkOrdersApp.Document')),
            ],
            options={
                'verbose_name_plural': 'Orders Status Documents',
                'verbose_name': 'Order Status Document',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Orders Status Photos',
                'verbose_name': 'Order Status Photo',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=Apps.WorkOrdersApp.models.get_upload_path)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkOrdersApp.Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Photos',
                'verbose_name': 'Photo',
            },
        ),
        migrations.CreateModel(
            name='RemarkStatusOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Remark Status Order',
                'verbose_name': 'Remark Status Order',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='remark',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='remarkstatusorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkOrdersApp.Order'),
        ),
        migrations.AddField(
            model_name='remarkstatusorder',
            name='remark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkOrdersApp.Remark'),
        ),
        migrations.AddField(
            model_name='remarkstatusorder',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkOrdersApp.Status'),
        ),
        migrations.AddField(
            model_name='remarkstatusorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderstatusphoto',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkOrdersApp.Order'),
        ),
        migrations.AddField(
            model_name='orderstatusphoto',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkOrdersApp.Photo'),
        ),
        migrations.AddField(
            model_name='orderstatusphoto',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkOrdersApp.Status'),
        ),
        migrations.AddField(
            model_name='orderstatusphoto',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderstatusdocument',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkOrdersApp.Order'),
        ),
        migrations.AddField(
            model_name='orderstatusdocument',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkOrdersApp.Status'),
        ),
        migrations.AddField(
            model_name='orderstatusdocument',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='remark',
            field=models.ManyToManyField(blank=True, null=True, through='WorkOrdersApp.RemarkStatusOrder', to='WorkOrdersApp.Remark'),
        ),
    ]
